// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfsaxhevshomxqckthoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmc2F4aGV2c2hvbXhxY2t0aG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxOTg1ODgsImV4cCI6MjA2Mjc3NDU4OH0.B43zXwjp0DHtUCRbs9DG783lkg11Xf6UC9GaQO9oZ2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);